### ISSUE TITLE
Logs wiggle up/down when scrolling past the last log

### ISSUE THREAD

**Issue by C0D3-M4513R** [grievouz/egui_tracing#7]
The log Ui will wiggle the logs up and down, if you scroll past the last log.
(original post used `egui_tracing` version 0.2.1)

(logs are up)
![image](https://github.com/grievouz/egui_tracing/assets/28912031/75f6096a-99cf-4c87-a25f-3aaf8ba18255)
(logs are down)
![image](https://github.com/grievouz/egui_tracing/assets/28912031/d4aca40c-10d1-48e0-803d-62e013b8ad95)

**Comment by grievouz** [comment]
Hi @C0D3-M4513R, thank you for creating this issue! To confirm, are you talking about the wiggling effect shown in the GIF below?

![example-eframe_ArG5xVcgTV](https://github.com/grievouz/egui_tracing/assets/24455496/df5478c2-fa84-4b83-8e95-a440cad0b156)

**Comment by C0D3-M4513R** [comment]
Yep. That kept happening on the last official release I tried. (I saw you merging/updating the egui version)

Also olease note, that I had no actual logs being pushed whilst that movement upd and down was happening.

Other than that I need to work on getting this working again with egui v0.27. last time I tried the logs were invisible (that was weeks before you merged the prs)

**Comment by C0D3-M4513R** [comment]
Yeah. `egui_tracing` just doesn't collect or display any log events for me anymore, since egui 0.27

![image](https://github.com/grievouz/egui_tracing/assets/28912031/7a592281-083a-452d-b774-4097f121679d)

The full application code is at: https://github.com/C0D3-M4513R/DexProtectOscRS/tree/testing/egui_tracing
(you will have to build with the `no_decryption_keys` feature enabled btw.)

**Comment by grievouz** [comment]
Yes, you're correct. When the GIF is slowed down, it's clear that the jumping occurs even when no new row is being rendered. This makes me suspect that the issue might be related to the `ScrollArea` widget in `egui`. I found a possibly related issue: https://github.com/emilk/egui/issues/3455. However, I need to do more investigation to confirm.

Regarding your issue with no logs, I'll check it out and if needed, I'll open a new issue to address it.

**Comment by C0D3-M4513R** [comment]
Don't. I just found it.
Typical facepalm moment...
https://github.com/C0D3-M4513R/DexProtectOscRS/commit/1995d451378782c1299c22e07be35bab812e8be0

**Comment by C0D3-M4513R** [comment]
It seems, that in the last version, this is not as noticeable anymore, because you cannot scroll past the end of the last log message anymore.

**Comment by grievouz** [comment]
If that's the case, I'll proceed with closing this issue. However, I've observed another related issue: after resizing the window/widget, the logs wiggle when aggregating new messages. I believe it's related to how I'm utilizing the scroll area. I'll create a new issue to track this separately. Let me know if you have any concerns, and thanks for your patience!
